services:
  server:
    image: heussd/fivefilters-full-text-rss:latest
    restart: on-failure
    environment:
      # Leave empty to disable admin section
      - FTR_ADMIN_PASSWORD=$APP_PASSWORD
      - PUID=1000
      - PGID=1000
    volumes:
      - /var/www/html/cache/rss
    ports:
      - 9169:80
    container_name: full-text-rss_server_1
